### PR TITLE
Consstring optimization

### PR DESCRIPTION
**Pull request by rbri**
Two minor optimizations
* there is no need to call a method because a simple cast is sufficient here
* the second one is more complex, in the else case we already have a parameter conversion loop that also flattens the ConsStrings. Because of this we do not need to run the loop for this branch

Have done the usual test with my HtmlUnit test suite a found no notable performance change. But reducing i think we have to do this to reduce the load a bit.

### CODE REVIEW

**Comment by rbri** [comment]
Sorry, looks like the second part introduces a problem. have to investigate this....

**Comment by rbri** [comment]
Hope this is now complete - waiting for feedback.

**Review by gbrail — APPROVED** [review]
Both of these optimizations look correct to me. Thanks!

**Comment by rbri** [comment]
Thanks will merge this also tomorrow (if no one complains)

**Pull request merged**
