### PR TITLE
implement #521 (padStart and padEnd)

### PR DESCRIPTION
**Pull request by rbri**
and some more cleanup and minor fixes.

### CODE REVIEW

**Comment by rbri** [comment]
Any hope for this one?

**Comment by gbrail** [comment]
Absolutely. Sorry for the delay. I'll look.

**Comment by gbrail** [comment]
In general... I think it's a good practice to separate changes that add or modify functionality from formatting changes. I know I'm always the one asking for commits to be squashed, but in this case I'd feel a lot better if the formatting changes and the String changes were separate PRs or at least separate commits.

Why? If we end up having to revert something or isolate a problem later it'll be easier if it's not all merged together into the same commit.

Is that a hard change to make? If it's a big burden we can go ahead anyway, but I think it's a good principle to follow.

**Comment by gbrail** [comment]
Ah -- they're already separate commits! Then never mind! I'll keep reading.

**Comment by rbri** [comment]
Thanks.

**Pull request merged**
