### PR TITLE
TypedArray and arguments are Iterable.

### PR DESCRIPTION
**Pull request by tuchida**
And fixed some specification violation.

### CODE REVIEW

**Comment by tuchida** [comment]
@eshepelyuk Sorry. Do I make a mistake in how to use your test?

**Comment by sainaen** [comment]
@tuchida 
I think what @eshepelyuk meant is that you can replace several ignores that share common prefix, with just one. For example,

     ! map-contract-expand.js
     ! map-contract.js
     ! map-expand-contract.js
     ! map-expand.js
     ! map.js

can be replaced with single

     ! for-of/map

Note: `! map` would also exclude files that are not excluded right now and have 'map' in the name, like  `arguments-mapped.js`.

**Comment by tuchida** [comment]
@sainaen
Thanks! I understood.

**Comment by sainaen** [comment]
Wait, but why did you add a `! map`? Isn't it ignores more than needed?

**Comment by tuchida** [comment]
Thanks!

partial matching
https://github.com/mozilla/rhino/blob/ce6771e502339c9a17809d8742b3d2af705464c7/testsrc/org/mozilla/javascript/tests/Test262SuiteTest.java#L149

**Comment by gbrail** [comment]
Merged to master and rebased. Thanks!

**Pull request closed without merging**
