### PR TITLE
Introduce column number in AST nodes

### PR DESCRIPTION
**Pull request by andreabergia**
This PR introduces column numbers in all AST nodes.
It also modifies the existing tests for the parser, and adds a lot more cases in a different class. I have gone through `Parser` measuring code coverage to ensure that the tests cover (almost) all the cases - the things I didn't really test are the non-standard things like xml, array comprehension, or let expression.

There is a breaking change: in case of a function call such as:

```js
a.
 b()
```

rhino will now assign line `1` to the expression, not line `2` (i.e. we assign the start of the expression, not the position of the parenthesis for the function call). This is for coherency with other parsers - I've checked what happen via https://astexplorer.net/ and it seems like the consensus is what I have implemented.

### CODE REVIEW

**Comment by rbri** [comment]
:-D Execution failed for task ':tests:spotlessJavaCheck'. :-D

**Comment by gbrail** [comment]
This is great progress and will help people in the future. Thanks for all the hard work here! I hope that we can next progress to getting column numbers in stack traces!

**Comment by p-bakker** [comment]
@andreabergia just FMI: was this change driver by the desire to properly support sourcemaps? See #1308

**Comment by p-bakker** [comment]
Also see #973

**Pull request merged**
