### PR TITLE
Fix the variable which has been defined null can not found, in script engine.

### PR DESCRIPTION
**Pull request by monrachen**
Changed the if condition from null-checking to Map::containsKey.

### CODE REVIEW

**Review by rbri — COMMENTED** [review]
Can you please add a test case for this.

**Comment by monrachen** [comment]
> 
> 
> Can you please add a test case for this.

**Comment by monrachen** [comment]
> 
> 
> Can you please add a test case for this.

[Test.txt](https://github.com/mozilla/rhino/files/5635932/Test.txt)
You can eval the js code in this file. It's the correct js code, but throw exception.

**Comment by gbrail** [comment]
Thanks -- I understand what you're trying to fix and it's small, but in order to merge this we need a test for it in the test suite that fails before the fix and works with the fix in. I'd suggest looking at the tests in:

https://github.com/mozilla/rhino/tree/master/testsrc/org/mozilla/javascript/tests/scriptengine

and either adding a new test or modifying an existing test. If you don't write a test case, then someone else has to do it, and that may take some time.

**Comment by monrachen** [comment]
> 
> 
> Thanks -- I understand what you're trying to fix and it's small, but in order to merge this we need a test for it in the test suite that fails before the fix and works with the fix in. I'd suggest looking at the tests in:
> 
> https://github.com/mozilla/rhino/tree/master/testsrc/org/mozilla/javascript/tests/scriptengine
> 
> and either adding a new test or modifying an existing test. If you don't write a test case, then someone else has to do it, and that may take some time.

Oh, sorry, I am the new. Should I cancel this pull request, create a new commit contain this fix and test case, then redo the pull request?

**Comment by gbrail** [comment]
Oh, no need to get rid of the pull request. Please either write a test case using one of the existing ones as a model, or modify an existing test case, and add whatever you changed as a new commit to this PR. Thanks!

**Comment by gbrail** [comment]
Ok -- I think this is an important fix and it's important that we get it right. If you look at an existing test case like this one:

https://github.com/mozilla/rhino/blob/8c6107b2c93d004fb77b0e3946085fe69060f18e/testsrc/org/mozilla/javascript/tests/scriptengine/ScriptEngineTest.java#L83

you'll see that it exercises the API, and then uses assertions to verify that it gets back what it expects. The test script that you added just runs some JavaScript code and doesn't actually use the Bindings class and doesn't assert anything.

I think what you're trying to fix can be tested with a test script like this:

  @Test
  public void testNulHandling() throws IOException, ScriptException {
    engine.put("shouldBeNull", null);
    engine.eval(new FileReader("testsrc/assert.js"));
    engine.eval("assertEquals(shouldBeNull, null);");
}

I would expect that this test or a similar one would fail without your fix, and then when you put the fix back in, it'll work.

**Comment by monrachen** [comment]
> 
> 
> Ok -- I think this is an important fix and it's important that we get it right. If you look at an existing test case like this one:
> 
> https://github.com/mozilla/rhino/blob/8c6107b2c93d004fb77b0e3946085fe69060f18e/testsrc/org/mozilla/javascript/tests/scriptengine/ScriptEngineTest.java#L83
> 
> you'll see that it exercises the API, and then uses assertions to verify that it gets back what it expects. The test script that you added just runs some JavaScript code and doesn't actually use the Bindings class and doesn't assert anything.
> 
> I think what you're trying to fix can be tested with a test script like this:
> 
> @test
> public void testNulHandling() throws IOException, ScriptException {
> engine.put("shouldBeNull", null);
> engine.eval(new FileReader("testsrc/assert.js"));
> engine.eval("assertEquals(shouldBeNull, null);");
> }
> 
> I would expect that this test or a similar one would fail without your fix, and then when you put the fix back in, it'll work.

Thanks for your guide, I had corrected it accroding by your tips, but the difference is I define the variable in js script.

**Review by gbrail — CHANGES_REQUESTED** [review]
Thanks for working on this. I think what's confusing me is that your test is just setting a variable in JavaScript -- that doesn't touch the Bindings object, which is the thing that you fixed. In order to verify that this fix actually fixes the bug, then you need to put a "null" value into the Bindings object using the Java API, don't you?

For example, if you take your fix out, then does the test case still pass? I think that it will.

**Comment by gbrail** [comment]
I still think that this is an important (and small) fix and that we should merge it. Is there anyone out there who would like to volunteer to create a good test case for it?

**Comment by gbrail** [comment]
I cherry-picked the commit in here that fixes ScriptEngine itself with a new test that I wrote and created a new PR: https://github.com/mozilla/rhino/pull/855. I'm going to close this one.

In other words, I'm going to merge the original fix to this problem into master but not using this particular PR. Thanks for fixing the original bug!

**Pull request closed without merging**
