### PR TITLE
fix Object.assign ToObject calls to use correct scope

### PR DESCRIPTION
**Pull request by tonygermano**
fixes https://github.com/mozilla/rhino/issues/842

### CODE REVIEW

**Comment by tuchida** [comment]
I could not find any test cases in test262 that validate this issue.

**Comment by tonygermano** [comment]
I couldn't either, but I did run all of the Object.assign tests from test262, and they passed after making my change. I think this is a rather odd way to call Object.assign in the first place, but the method signature of ScriptRuntime.toObject that is being called is `toObject(Context cx, Scriptable scope, Object val)`, so I think it was a mistake to be passing `thisObj` instead of `scope` as the scope to begin with.

**Comment by tuchida** [comment]
> but I did run all of the Object.assign tests from test262, and they passed after making my change.

:+1: 

In the other `Object` methods, it seems to call `getCompatibleObject` instead of `ScriptRuntime.toObject` directly.
https://github.com/mozilla/rhino/blob/61493d5aca90f537058ac873f0fd9987d494d7e4/src/org/mozilla/javascript/NativeObject.java#L606-L613

However, `Object.assign` doesn't exist in ES5, so I think it doesn't matter either way.
https://262.ecma-international.org/5.1/#sec-15.2

**Comment by gbrail** [comment]
This makes sense but I want to make sure that we have test coverage. Is there a test case that failed before you fixed this that we can add somewhere in the test suite?

**Comment by tonygermano** [comment]
There is a test in referenced issue https://github.com/mozilla/rhino/issues/842

```javascript
var NISLFuzzingFunc = function (nislMutationParameter0) {
    return Object.assign.apply(null,nislMutationParameter0);
};
var nislMutationArgument0 = [1,2,3,4];
var NISLCallingResult = NISLFuzzingFunc(nislMutationArgument0);
print(NISLCallingResult);
```
I'm not sure of the appropriate place to add it.

**Comment by tonygermano** [comment]
So I wrote a .jstest for this, and it actually passed. I'm not sure what language level those tests run at, but it looks like the test case in the issue fails on version 180 or 200, and passes on <180.

I tracked it down to here, where older versions apparently don't let you use `call` or `apply` with a null `this`.
 https://github.com/mozilla/rhino/blob/399b9f05a8effd48f105afc25e7f4a5dd8ffebf7/src/org/mozilla/javascript/ScriptRuntime.java#L2755-L2757

I'm not sure what to think about it passing at lower language versions, since Object.assign is technically an ES6 feature, anyway.

I just pushed a new commit with a test using `ScriptTestsBase` and `RhinoTest`, which does work. Is this the preferred way to write a test? I probably found 5 or 6 different ways that tests are bring run. Is there any guidance on writing tests? Which testing method to use, where to put them, naming conventions, etc...

**Comment by gbrail** [comment]
Those tests look fine to me and setting them up the way that you did to make it work with ES6 only is fine. Thanks!

**Pull request merged**
