### PR TITLE
simplify tests

### PR DESCRIPTION
**Pull request by rbri**
a bit of test simplification and format unification

### CODE REVIEW

**Comment by gbrail** [comment]
Thanks for doing this!

If you have a chance, take a look at https://github.com/mozilla/rhino/pull/1760 and I can merge it -- it creates a new module for that pesky "Utils" class and we can put other common test code there too if it makes sense.

**Comment by rbri** [comment]
@gbrail please merge the util, will update this over the weekend

**Comment by rbri** [comment]
@gbrail hopefully ready to merge

**Comment by gbrail** [comment]
Thanks -- this is the kind of unglamorous work that every open source project needs!

**Pull request merged**
