### PR TITLE
Update NativeDate.java

### PR DESCRIPTION
**Pull request by Jugolo**
I has calculate it and sometime this will fail and this should fix it

### CODE REVIEW

**Comment by gbrail** [comment]
Thanks for submitting this. It's a pretty critical piece of code, however,
and it's hard to accept this PR without more information, such as:

   - A test that failed previously and is fixed with this change
   - Some context as to why you uncovered this issue
   - Some assurance that the change doesn't break anything else.

Thanks -- if you can help with some of this info, then we can see about
merging it.

**Comment by Jugolo** [comment]
Okay i will came with a math exempel later :)

**Comment by Jugolo** [comment]
Okay the time is 1482314077000
wee method Day will return: 17156
Year will be 2016

First wee will calculate Day-Year
So
 17156
-2016
=15140

Wee do anthoer calculate
 15140
-59
=15081

And finaly
 15081
/30
=9.8666666666667

So it need to be round up so it is 10

**Comment by Jugolo** [comment]
Hi sorry i ask but any news?

**Comment by gbrail** [comment]
OK -- this looks reasonable and the tests are good. Trying to get back into a few regular Rhino updates.

**Pull request closed without merging**
