### PR TITLE
fix clz32 rounding errors

### PR DESCRIPTION
**Pull request by rbri**
use bit logic to avoid rounding errors  (based on https://github.com/HtmlUnit/htmlunit-rhino-fork/pull/10)

### CODE REVIEW

**Comment by gbrail** [comment]
Do you know if there's a test from test262 or anything that can verify this? For example, there is a "math-clz32.js" file in the V8 codebase, but it seems much different than this. I'm sure that this is right but I'd feel better if we had a reference.

**Comment by rbri** [comment]
> there is a "math-clz32.js" file in the V8 codebase, but it seems much different than this

yes, found the same while preparing this

**Comment by rbri** [comment]
> Do you know if there's a test from test262 or anything that can verify this?

Will have another look but i think i can't spend so much time on this and running all the samples in the browser proof that this is correct.

**Comment by rbri** [comment]
@gbrail looks like 262 has only tests for the border cases of Math functions (see PR #1438). Maybe we have to roll our own.

**Comment by gbrail** [comment]
OK - I think we're in good shape here then. Thanks!

**Pull request merged**
