### PR TITLE
Math.max/min - each element coerced

### LINKED ISSUE #781: An issue about the Math.max().
**Revision**

rhino-1.7.13

**Test case**

```javascript
var NISLFuzzingFunc = function(){
    var a = {
        valueOf: function(){
            print(1);
        }
    };
    var b = Math.max(NaN,a);
};
NISLFuzzingFunc();
```

**Execution steps**

```javascript
java -jar rhino/rhino-1.7.13.jar -debug -version 200 testcase.js
```

**Output**

```javascript
No output.
```

**Expected behavior**

```javascript
Output 1.
```

**Description**

When I passed NaN and an object with the "valueOf" attribute value as a callable function to the first and second parameters of Math.max, chakra did not execute this function. According to the ES standard, the ToNumber operation is performed on each parameter of Math.max, and the "valueOf" attribute value function of the second parameter will be executed.

Contributor : @Haobin-Lee

### PR DESCRIPTION
**Pull request by morfav**
I wasn't sure about tests, I did submit a PR to test262 however not sure if that will ever get accepted.

This is my first contribution, please let me know if there is anything I should improve.

Thanks!
Vlad

resolves #781

### CODE REVIEW

**Comment by gbrail** [comment]
Thanks -- I appreciate that you looked at test262 as well.

We do need a test for this in the test suite somewhere. The first choice would be to enable an existing test in the test262 test suite by uncommenting some tests in test262.properties. The second would be to add a test in our own test suite. If you follow the pattern in https://github.com/mozilla/rhino/tree/master/testsrc/org/mozilla/javascript/tests then that's not too much work.

If this isn't already covered in test262, then can you show us where in the spec it says that Rhino is doing this incorrectly, or to different behavior in the "more popular" script engines?

Thanks -- it's a lot of work but we're trying to be consistent with all this since a lot of people depend on Rhino. Thanks for contributing!

**Comment by gbrail** [comment]
Sorry -- I forgot that the attached issue clearly explains the problem and associated spec, so don't worry about "why should we fix this." But please do add a test case based on the example in that issue.

**Comment by morfav** [comment]
Is this what you had in mind? Is @LanguageVersion(Context.VERSION_DEFAULT) appropriate?

**Comment by gbrail** [comment]
Yes -- that looks like what I was thinking of. I'll look at it and merge it soon.

**Comment by gbrail** [comment]
This looks good. Thanks!

**Pull request merged**
