### PR TITLE
Update LIST

### PR DESCRIPTION
**Pull request by petergrewsome**
added run after regexp-dna

### CODE REVIEW

**Comment by p-bakker** [comment]
Whats the background of this PR?

**Comment by gbrail** [comment]
I suspect that this must be related to trying to run the SunSpider benchmarks the old, manual way.

I have been running these too and just updated the benchmark framework in another PR -- perhaps that's what you want:

https://github.com/mozilla/rhino/pull/1559

**Comment by petergrewsome** [comment]
Thanks

**Comment by p-bakker** [comment]
Closing this assuming #1559 resolved this

**Pull request closed without merging**
