### PR TITLE
Fixes Parser.throwStatement()

### PR DESCRIPTION
**Pull request by stijnkliemesch**
Fixes Parser.throwStatement() creating ThrowStatement with incorect length

### CODE REVIEW

**Comment by stijnkliemesch** [comment]
The created ThrowStatement had its length property initialized with not a length value but the ASTNode's endposition value.

**Comment by gbrail** [comment]
Very straightforward and it doesn't break anything. However in the service of making this codebase better over time I'd still love to see a new test case. Thanks!

**Comment by stijnkliemesch** [comment]
The testcase triggers a specific use of the ThrowStatement instance that, without the fix, ends up using the incorrect value.

This case is how I encountered the bug, I suppose the bug mentioned in the testcase commit message should have been a seperately reported issue before initiating this pull request.

**Comment by gbrail** [comment]
Thanks for the test case!

**Pull request merged**
