### PR TITLE
Issue #511, fixing InterfaceAdapter abstract name lookup.

### PR DESCRIPTION
**Pull request by GuillermoBlasco**
Solving issue #511. Now default methods are ignored, so they do not conflict with
interface (abstract) methods to implement.

### CODE REVIEW

**Comment by gbrail** [comment]
Would it be possible to add a test case so that this doesn't regress? For instance, it looks like we have some default method tests already in testsrc/jstests/java8/call-default-method.js

**Comment by Jeffrey-P-McAteer** [comment]
Hi has there been anything blocking this fix from being merged in? I'm in a position at work where having this engine accept callback functions as `Consumer<T>` objects would be useful.

**Comment by GuillermoBlasco** [comment]
Hi @Jeffrey-P-McAteer 
Nothing but the missing tests :D anyhow I've been using rhino with that fix during almost a year and worked like a charm.

**Comment by rPraml** [comment]
I ran into the same issue

**Comment by tonygermano** [comment]
Suggest closing this as superseded by https://github.com/mozilla/rhino/pull/631

**Comment by p-bakker** [comment]
Closing as superceded by #631

**Pull request closed without merging**
