### PR TITLE
Make sure setting "functionName = null" is propagated to thisObject.

### PR DESCRIPTION
**Pull request by rbri**

### CODE REVIEW

**Comment by gbrail** [comment]
Sounds like a good compatibility fix, and I doubt that it will break old stuff. 

However, could you improve the commit message so that it tells what it fixes? That'll be the basis of the release notes (or, update this PR at least). That way people will know what happens if they did indeed affect this.

**Comment by rbri** [comment]
Ok, what about:

Make sure setting "functionName = null" is propagated to thisObject

**Comment by rbri** [comment]
@gbrail any hope for this?

**Comment by gbrail** [comment]
Yes, there is always hope. And thank you!

**Pull request merged**
