### PR TITLE
Build with Gradle

### LINKED ISSUE #168: Make Project IDE Friendly
While this project runs from the command line easily, IDE integration (specifically IntelliJ) isn't straight forward. The easiest way to implement this would probably be with Maven (see #57).

In the meantime, is it possible to add some instructions?

### LINKED ISSUE #178: Implement build system with Gradle
Hello @gbrail 
A you mentioned in mailing list - it would be good to migrate build system to either `Maven` or `Gradle`.
I'd like to tackle the task of implementing project build with `Gradle`. 
Although not promising that it could be really fast but if you see agree I'd like to start it now.
It also could solve Issue #168 

I am also interested to know your opinion about directory structure. Can I change it to be Maven / Gradle compatible, i.e. looking like src/main/java, src/main/resources etc.

What do you think ?

### PR DESCRIPTION
**Pull request by eshepelyuk**
MIgration of build system to `Gradle`.
Some unit tests were modified, 1 unused was deleted to make `Gradle` adoption easier.
fixes #178 fixes #168 

Closes #57

### Done
* usage of [Gradle wrapper](http://gradle.org/docs/current/userguide/gradle_wrapper.html), no local `Gradle` installation needed
* compile sources and tests with `Gradle`
* run unit tests and benchmark testing
* publishing to `Maven` compatible repositories with `Gradle`
* legacy `Ant` and `Maven` scripts are still working
* support of quick import from IDE, especially `IntelliJ IDEA` due to `Gradle` project nature

### Postponed for further review, until PR approval
* code structure reorganization
* deletion of legacy scripts
* `README` updates
* usage of default build directory, now custom folder `buildGradle` is used to prevent conflicts with `Ant`

### Not planned
* creating `ZIP` artifacts like one currently produced by `Ant`. It seems no need to have one
* `release` management, i.e. automatic version update, creating GIT tags etc
* `EMMA` test code coverage

### CODE REVIEW

**Comment by eshepelyuk** [comment]
Hello @gbrail, could you review the PR and provide your feedback.
Thnx in advance.

**Comment by gbrail** [comment]
Working on testing this -- I hope to get more time next week.

Can you try and figure out why I have to put a bunch of Maven stuff in my global "gradle.properties," including a repo URL, username, and password? I think that if we want everybody to use this (and we do) then they shouldn't have to configure that stuff. I can give details if you want...

**Comment by eshepelyuk** [comment]
Hello, 
That's the thing I've missed to describe. You're right - there's no need to put those properties into `gradle.properties` of root folder.

Just create a file `${HOME}/.gradle/gradle.properties` and put repository URLs and credentials properties there. This is how it is intended to work.

I'll update `README.md` with `Gradle` related changes soon.

**Comment by gbrail** [comment]
Is there a way to write the Gradle files so that those properties are
optional? Most people building this product won't have those.

On Wed, Apr 29, 2015 at 9:19 AM, Evgeny Shepelyuk <notifications@github.com>
wrote:

> Hello,
> That's the thing I've missed to describe. You're right - there's no need
> to put those properties into gradle.properties of root folder.
>
> Just create a file ${HOME}/.gradle/gradle.properties and put repository
> URLs and credentials properties there. This is how it is intended to work.
>
> I'll update README.md with Gradle related changes soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/pull/179#issuecomment-97486120>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by eshepelyuk** [comment]
Pushed the fix, plz update.

**Comment by gbrail** [comment]
Making good progress...

I think that there are two more things we should do:

First, of all the "compile" ant task (on line 43 of build.xml) copies all the source into the build directory before compiling, and uses an ant "filter" task to replace the macro @IMPLEMENTATION-VERSION

**Comment by gbrail** [comment]
...

First, of all the "compile" ant task (on line 43 of build.xml) copies all the source into the build directory before compiling, and uses an ant "filter" task to replace the macro @IMPLEMENTATION-VERSION@ with the version from build.properties. Without doing this macro replacement, then you get this:

$ java -jar buildGradle/libs/rhino-1.7.7-SNAPSHOT.jar
@IMPLEMENTATION.VERSION@
js>

Instead of:

Rhino 1.7.7 2015 04 30
js>

Gradle can do this -- or we can find a better way since it's just one property in one file (it could look it up from the JAR manifest I think). But either way we should do it.

Second, we have always distributed the result of "ant dist" on the Mozilla web site, so if we want to remove ant and put in gradle instead, then we should include the ZIP file that results from this command.

Also, it'd be nice if there was an equivalent of "ant junit-benchmarks". But that can come later.

If you can fix the IMPLEMENTATION.VERSION easily, then I think we should merge this. Then we can see about removing the ant stuff.

**Comment by eshepelyuk** [comment]
1. As I've mentioned in PR description, we can run benchmark tests with Gradle. Just try to run `gradlew testBenchmark`.
2. IMPLEMENTATION_VERSION will be implemented.
3. About `zip` archive, what is the purpose of distributing it ? Should it be published to Maven repo as artifact ? What should be the content of that file ? I just see no good reasons now to copy ant behaviour since we could just zip jars produced for publishing to maven. Please give me some clues about this archive purpose.

P.S. I will be able to provide fixes only starting from Monday.

**Comment by gbrail** [comment]
OK -- no worries. I can do a few things to fix it. I don't like the way that we filter ALL the source anyway so I'm going to change it in ant and then in Gradle. No need to do anything until you hear from me.

**Comment by eshepelyuk** [comment]
Well, maybe if you can wait couple if days I will push those fixes. I am planning to do in in Java and remove it from build script responsibilities.

**Comment by gbrail** [comment]
Of course, and we can take our time to get this right.

I made a small change and pushed it to a build called "greg-gradle." If you (having a lot more Gradle experience than I) think that it solves the immediate problem, then I think we can push this to master and then iterate from there.

Can you take a look:

https://github.com/mozilla/rhino/blob/greg-gradle/build.gradle

Basically, I added a task to copy the contents of "src/org/mozilla/javascript/resources" into the build directory, with filtering -- without that, the message property bundle was missing.

WIth this change, other than the "dist.zip" I think that we have Gradle doing everything that Ant did.

**Comment by eshepelyuk** [comment]
Looks good, not sure we need `afterEvaluate` closure.

**Comment by eshepelyuk** [comment]
Pushed fix to obtain `Rhino` display version from `MANIFEST.MF`

**Comment by eshepelyuk** [comment]
@gbrail have you ever expirienced failures in `MozillaSuiteTest`.
I see some tests are failing from time to time either running with `Ant` or `Gradle`.
But the failing tests are non permanent. They are failing just from time to time.

**Comment by gbrail** [comment]
Yes, there are a few tests that are timing-related. For instance, there is
one now that fails because it expects a certain performance characteristic
from global variables. It is not consistent. I'm not sure what to do about
these but we do have a few right now.

Interestingly, some of them perform differently when run via ant versus
gradle, which is especially strange.


On Mon, May 4, 2015 at 12:01 PM, Evgeny Shepelyuk <notifications@github.com>
wrote:

> @gbrail <https://github.com/gbrail> have you ever expirienced failures in
> MozillaSuiteTest.
> I see some tests are failing from time to time either running with Ant or
> Gradle.
> But the failing tests are non permanent. They are failing just from time
> to time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/pull/179#issuecomment-98813842>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by eshepelyuk** [comment]
1. `Gradle` uses own tools for running `JUnit` and I've tried to emulate all the options from `Ant` build, we can't be confident that runners behave the same way.
1. `Gradle` uses some daemon process and caches when running build, so it could affect build
1. And last but not the least - `Gradle` should consume more PC resources on its own and it could affect GC cycles, thus affecting those tests.

**Comment by gbrail** [comment]
I am, however, seeing a null pointer exception in the re-factored
"ComplianceTest" that only happens when running on the CI machine, and not
locally:

http://ci.apigee.io/job/Mozilla%20Rhino%20Custom%20Branch/25/testReport/junit/org.mozilla.javascript.tests.commonjs.module/ComplianceTest/initializationError/

I'm not sure what's going on unless the directory that it's looking up in
line 34 doesn't exist or is not a directory.


On Mon, May 4, 2015 at 12:01 PM, Evgeny Shepelyuk <notifications@github.com>
wrote:

> @gbrail <https://github.com/gbrail> have you ever expirienced failures in
> MozillaSuiteTest.
> I see some tests are failing from time to time either running with Ant or
> Gradle.
> But the failing tests are non permanent. They are failing just from time
> to time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/pull/179#issuecomment-98813842>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by eshepelyuk** [comment]
Could you check if files really exists in job's build folder ! I can't access it on my own.
Btw, the job still executes `Ant`, not Gradle. Is it intentional ?

**Comment by eshepelyuk** [comment]
I've given up struggling to create PullRequest to `eshepelyuk-gradle` branch with fix.
So could you change `CompianceTest` line 34 

from
```
final File[] files = new File(ComplianceTest.class.getResource("1.0").getPath()).listFiles();
```

to
```
final File[] files = new File("testsrc/org/mozilla/javascript/tests/commonjs/module/1.0").listFiles();
```

**Comment by eshepelyuk** [comment]
@gbrail Some more questions

1. Earlier I've asked about clarifications of the purpose of ZIP archive
> About zip archive, what is the purpose of distributing it ? 
> Should it be published to Maven repo as artifact ? What should be the content of that file ? 
> I just see no good reasons now to copy old ant behaviour since we could just zip jars produced for publishing to maven. 
> Please give me some clues about this archive purpos

1. Do you mind including support for [Spock testing framework](http://spockframework.github.io/spock/docs/1.0/index.html) to the project together with `Gradle` adoption ?

**Comment by gbrail** [comment]
OK -- I fixed that and merged. Thanks for all the work on this!

**Pull request closed without merging**
