### PR TITLE
Reformat Global.java for future modifications.

### PR DESCRIPTION
**Pull request by MaxisTekfield**
As the title says, this PR reformats `Global.java` for other PRs like #1103 .

### CODE REVIEW

**Comment by p-bakker** [comment]
Thnx

Not sure if you're aware, but we're holding of merging anything atm, until 1.7.14 final is released

**Comment by MaxisTekfield** [comment]
It's OK. I'am wondering when will v1.7.14 be released?

**Comment by p-bakker** [comment]
See #1088

**Comment by gbrail** [comment]
Yes, let's not add any new features until we get through the 1.7.14 release process -- it's going to be hard to maintain a branch for that in the long run so I'd like to only include bug fixes for the next week or so.

**Comment by gbrail** [comment]
This is very low risk so let's do it now. Thanks!

**Pull request merged**
