### PR TITLE
make sure the this object is coercible for String.prototype.big and similar calls

### LINKED ISSUE #765: An issue about String.prototype.big
According to ES6.0, when using method [[call]] to modify 'this' of `String.prototype.big`, update 'this' into 'null' or 'undefined' will raise a TypeError. And many other methods like `String.prototype.small`, `String.prototype.fontsize`, which are defined in Annex B have the same situations. This may be an issue of Rhino.

#### version

```
1.7.12
```

#### command

```
java -jar rhino/rhino-1.7.12.jar -debug -version 200 testcase.js
```

#### testcase

```javascript
var v0 = function(){
    return String.prototype.big.call(null);
};
var result = v0();
print(result);
```

#### output

```
<big>null</big>
```

#### expected output

```
TypeError: big: 'this' is null or undefined
```

contributor:[@YuanWangC](https://github.com/YuanWangC)

### PR DESCRIPTION
**Pull request by rbri**
add missing attribute escaping for all the methods

fixes #765

### CODE REVIEW

**Comment by rbri** [comment]
@gbrail please this also - or do you have any concerns about backward compatibility?

**Comment by gbrail** [comment]
I am always worried about backward compatibility ;-) However this particular use is obscure enough that I think it's fine for us to just update and start matching the spec. (I didn't know about these special prototype functions either!)

**Comment by rbri** [comment]
> I am always worried about backward compatibility

I'm always worried about your worries about backward compatibility :-)

> However this particular use is obscure enough that I think it's fine for us to just update and start matching the spec.

Yes strange stuff from the good old days.

> (I didn't know about these special prototype functions either!)

Same here - but i fear they are still in use somewhere (e.g. nuclear power plants)

**Comment by rbri** [comment]
Oh BTW: - Thanks for merging

**Pull request merged**
