### PR TITLE
Improved Test262SuiteTest; many more tests

### PR DESCRIPTION
**Pull request by rbri**
hack to dump already passing tests
exclude one more class of tests
more tests are passing

### CODE REVIEW

**Comment by rbri** [comment]
Hi Greg,
after reading the doc a bit more careful a some coffee if made the right change to our travis build setup.
Hope you agree and we can have this larger tests suite as part of our build.

**Comment by gbrail** [comment]
I got some OOM errors on the Regexp tests just now on my workstation. I have to run but will try again and see if it's repeatable... (built-ins/RegExp/S15.10.2...)

**Comment by rbri** [comment]
But travis was green and i can't remember to see an oom while testing. JDK 1.8?

**Comment by gbrail** [comment]
it works better if I increase the heap size in build.gradle from 256 MB to 1 GB, which is still reasonable IMHO given that we are now running more than 80,000 tests. I'm going to check that in and then merge this.

**Pull request merged**
