### PR TITLE
ensureScriptable(..) and ensureScriptableObject(..) have to take care of Delegator instances

### PR DESCRIPTION
**Pull request by rbri**
Next try hope this is correct now.

### CODE REVIEW

**Comment by gbrail** [comment]
I'm not super excited about the way that this is going. It seems that we'd have to end up calling "getDelegee" every place in the codebase where we might have a Delegate, and then that kind of defeats the purpose of this feature. I thought that the idea of Delegate was just to have some way to put another Scriptable in front of another, and in turn that would solve a large number of use cases.

Perhaps with some examples of what you're trying to do we can figure out how to best solve the problem.

**Comment by rbri** [comment]
He he, making you super excited was not the idea of this pull request.
And yes i understand your point. While looking at the source a found many more places where i have the feeling there is a need to handle this Delegator instances also.

But: All changes in this pull request are changes we did already in the HtmlUnit for; all this changes where done on demand - means we had some problem at this special places.
As far as is remember we use this Delegator instance only for a single class. We made several attempts in past to get rid of this but there was some good reasons to stay with the delegator. I will not start looking the whole code and add Delegator instance checks all over. But it will be great if we can add this patch because we already know that we have to handle the Delegators at this places. There is some risk that we will find more in the future but this is a different story.

**Comment by gbrail** [comment]
OK -- just looking at the benchmarks since this also introduces a bunch more instanceof checks on every function invocation.

My other concern is that we don't have a test for this. I think we really need a test case that failed before and passes with this change. Otherwise there is nothing stopping future developers from breaking this again.

**Comment by p-bakker** [comment]
Not exactly sure how the Delegator class would be used, but it looks similar to JavaScript Proxies

Wondering if Proxies could replace Delegator or help in any way, by maybe Delegator extending Proxy

Just thinking out loud

**Comment by rbri** [comment]
Yes the Delegator is some kind of a proxy but i fear this is in use not only by HtmlUnit.
Will try to find/create a test case for this.

**Comment by rbri** [comment]
Will close this - because i have prepared a new one (less changes and including tests)

**Pull request closed without merging**
