### PR TITLE
force LF as newLine character

### PR DESCRIPTION
**Pull request by p-bakker**
spotlessApply would otherwise convert all newLine characters to CRLF on
windows

Closes: #918

### CODE REVIEW

**Comment by gbrail** [comment]
This is of course a fine idea but I am worried since we have files in the test directories (and some test262 files) with CRLF line endings. What happens on Windows when one checks those out with this flag set? And do all the tests run on Windows?

I don't have Windows set up to test this, unless it's using Ubuntu on Windows which I assume still uses LF.

**Comment by p-bakker** [comment]
@gbrail  I'll get back to you on that one

**Comment by tonygermano** [comment]
Would it make sense to only set `eol=lf` for `*.java` files?

**Comment by gbrail** [comment]
Definitely -- that's lower risk I think.

**Comment by p-bakker** [comment]
Surpassed by #1584

**Pull request closed without merging**
