### PR TITLE
Delete idswitch

### PR DESCRIPTION
**Pull request by tuchida**
ref.  #878
Removed idswitch because it does not support spotless, and also because it is now using string switch from #847.

### CODE REVIEW

**Comment by rbri** [comment]
If my memories are correct we can use in most of the cases a pattern like

    case "constructor":
        return Id_constructor;

instead of assigning a var and returning later.
There are only two or there classes where this simplification does not work.

**Comment by gbrail** [comment]
How do others watching this PR feel about all this reformatting? This PR basically reformats every file that had an idswitch tag in it.

I'm actually OK with it but I wanted to make sure that it won't impact anyone else who is on the verge of having to merge something big.

**Comment by rbri** [comment]
Ok for me, at the moment i have a hard time with all the merges with my rhino fork. Will be great if the reformat ends soon - so this brings me closer to the light at the end of the tunnel.

**Comment by gbrail** [comment]
Just looking at the queue of incoming PRs, there's going to be a lot of merging going on if we import such a large set of formatting changes at once. I'd rather just get rid of the idswitch tool now, and then remove the annotations more gradually as we change other things.

**Comment by gbrail** [comment]
Ok, I'm sold on ripping off the Band-Aid sooner in this case. Thanks for all the work to pull this together!

**Pull request merged**
