### PR TITLE
 Catch ParserException in IRFactory

### LINKED ISSUE #967: Resolve structural issue with exception handling in IRFactory
In the example below, one can see that the `IRFactory` throws a `ParserException` when in this case a `SyntaxException` ought to be thrown. 

Further down comment https://github.com/mozilla/rhino/issues/967#issuecomment-874616417 points to a fix that results in the proper Error being thrown, but proper location info is missing.

These issues ought to be fixed, possibly requiring the refactoring of the `IRFactory` as suggested below

https://github.com/mozilla/rhino/pull/853#issuecomment-813031347
If I evaluate `1=1`, I will expect only JavaScript error, but Java exception will be thrown.
```
$ java -jar buildGradle/libs/rhino-1.7.14-SNAPSHOT.jar
Rhino 1.7.14-SNAPSHOT 2021 06 29
js> 1=1
js: line 1: Invalid assignment left-hand side.
js: 
js: ^
Exception in thread "main" org.mozilla.javascript.Parser$ParserException
	at org.mozilla.javascript.Parser.reportError(Parser.java:329)
	at org.mozilla.javascript.Parser.reportError(Parser.java:315)
	at org.mozilla.javascript.Parser.reportError(Parser.java:310)
	at org.mozilla.javascript.IRFactory.createAssignment(IRFactory.java:2309)
	at org.mozilla.javascript.IRFactory.transformAssignment(IRFactory.java:448)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:222)
	at org.mozilla.javascript.IRFactory.transformExprStmt(IRFactory.java:559)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:219)
	at org.mozilla.javascript.IRFactory.transformScript(IRFactory.java:1133)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:201)
	at org.mozilla.javascript.IRFactory.transformTree(IRFactory.java:121)
	at org.mozilla.javascript.Context.parse(Context.java:2437)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2354)
	at org.mozilla.javascript.Context.compileString(Context.java:1368)
	at org.mozilla.javascript.Context.compileString(Context.java:1356)
	at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:495)
	at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:181)
	at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:101)
	at org.mozilla.javascript.Context.call(Context.java:534)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:472)
	at org.mozilla.javascript.tools.shell.Main.exec(Main.java:163)
	at org.mozilla.javascript.tools.shell.Main.main(Main.java:138)
```

`Parser$ParserException` is private class. There is something strange about this being thrown out of `Parser`.

There are probably two problems with this. (I'm sorry if I'm wrong.)

### 1. `IRFactory` inheritance of `Parser`

This makes it difficult to know where to catch the `Parser$ParserException`. 
I felt that `IRFactory` inheritance of `Parser` was an anti-pattern of Code reuse via inheritance.

### 2. Reanalyzing the entire AST.

Rhino parser seems to work as follows.

1. `Parser` make AST from source code.
2. Within `IRFactory`, `Decompiler` reverts the all AST to source code.
3. `IRFactory` and `Parser` will reanalyze the source code.

The syntax of ECMAScript is ambiguous and some things need to be reanalyzed.
https://262.ecma-international.org/12.0/#sec-syntactic-grammar
> In certain cases, in order to avoid ambiguities, the syntactic grammar uses generalized productions that permit token sequences that do not form a valid ECMAScript Script or Module. For example, this technique is used for object literals and object destructuring patterns. In such cases a more restrictive supplemental grammar is provided that further restricts the acceptable token sequences. Typically, an early error rule will then define an error condition if "P is not covering an N", where P is a Parse Node (an instance of the generalized production) and N is a nonterminal from the supplemental grammar. Here, the sequence of tokens originally matched by P is parsed again using N as the goal symbol. (If N takes grammatical parameters, then they are set to the same values used when P was originally parsed.) An error occurs if the sequence of tokens cannot be parsed as a single instance of N, with no tokens left over. Subsequently, algorithms access the result of the parse using a phrase of the form "the N that is covered by P". This will always be a Parse Node (an instance of N, unique for a given P), since any parsing failure would have been detected by an early error rule.

However, it should only be necessary to reanalyze the grammar that write "cover".

> P is not covering an N

### PR DESCRIPTION
**Pull request by tuchida**
Closes #967
Errors in `IRFactory` have the following issues.

1. `Parser$ParserException` not caught.
   ```
   js> 1=1
   js: line 1: Invalid assignment left-hand side.
   js: 
   js: ^
   Exception in thread "main" org.mozilla.javascript.Parser$ParserException
   	at org.mozilla.javascript.Parser.reportError(Parser.java:340)
   	at org.mozilla.javascript.Parser.reportError(Parser.java:326)
   	at org.mozilla.javascript.Parser.reportError(Parser.java:321)
   	at org.mozilla.javascript.IRFactory.createAssignment(IRFactory.java:2325)
   ```
2. Wrong line position.
   ```
   js> var a = 1;
   var b = 2;
   const [c, c] = [3, 4];

   js> js> js: line 1: TypeError: redeclaration of const c.
   ```

`IRFactory` is re-parsing ASTs that have already been parsed by `Parser`, but the error thrown at that time was not handled properly.
So, I have fixed 0cd0e2b2bc662cbcf560d03a3cc9794792bb40d1 for 1. and 436d3f62f0ff4f92f614ef58fdbc7a1bc887ed8c for 2.

### CODE REVIEW

**Comment by gbrail** [comment]
Thanks -- this looks really nice and I'm glad you did it.

I'm trying to also improve code coverage across the board, and from running "./gradlew testCodeCoverageReport" I can see that there are a few spots in IRFactory that we aren't testing. Specifically, there's some new exception-handling code around line 129 of IRFactory.java that doesn't seem to be hit by any of the tests. Would it be possible for you to come up with some sort of test code that would help us hit that spot? 

Specifically, from looking at the coverage report, the part below in "transformTree" is new code, it seems pretty important, and it seems to be missing coverage.

        ScriptNode script = null;
        astNodePos.push(root);
        try {
            script = (ScriptNode) transform(root);
        } catch (Parser.ParserException e) {
            // Doesn't seem to have any code coverage here...
            parser.reportErrorsIfExists(root.getLineno());
            return null;
        } finally {
            astNodePos.pop();
        }


Thanks!

**Comment by tuchida** [comment]
@gbrail I added test to see if `runtimeError` was called ref. 6480350022227b0456bf13dee9ea7865f8736e66. However, the result of `./gradlew testCodeCoverageReport` did not change. What should I do?

**Comment by gbrail** [comment]
Well there might be more for me to investigate, then, since I just replaced
those non-covered lines with an AssertionError and the tests failed. So
that tells me that the code coverage report could itself use some code
coverage ;-)

Given that, I'm happy to merge this as long as it doesn't conflict with
your other big PR for IRFactory!

**Comment by p-bakker** [comment]
Hi @tuchida while rummaging though the backlog of issues, I ran into the following issues of which I wonder if this PR either resolved them or at least moves the needle somewhat: 
- #405 
- #406
- #989 
- #1187

**Comment by tuchida** [comment]
@p-bakker #405 was fixed. Others remained the same or had other errors.

**Comment by gbrail** [comment]
This is great and thanks for doing it!

**Pull request merged**
