### PR TITLE
Fix issue #1041. Handles {0} quantifier with max of zero correctly.

### LINKED ISSUE #1041: RegExp does not handle quantifier with max of zero correctly
```js
js> var re = /ab{0}c/
js> re.test('abc')
true
```
Expected: `false`

### PR DESCRIPTION
**Pull request by MaxisTekfield**
I've fixed the issue #1041 .

Closes #1041

### CODE REVIEW

**Comment by p-bakker** [comment]
Thnx for your contribution!

I see that you included a unit test: isn't this JavaScript behavior covered by a test in the Test262 suite, that was failing and now started passing?

**Comment by MaxisTekfield** [comment]
> 

I'll check test262 later.

**Comment by MaxisTekfield** [comment]
> Thnx for your contribution!
> 
> I see that you included a unit test: isn't this JavaScript behavior covered by a test in the Test262 suite, that was failing and now started passing?

I cannot find any corrsponding test in test262. Only `test262/implementation-contributed/v8/mjsunit/third_party/regexp-pcre/regexp-pcre.js` has some cases as follows:
```javascript
// ...
res[903] = /a{0}bc/;
// ...
assertToStringEquals("bc", res[903].exec("bc"), 2782);
// ...
```

It seems that we don't run any cases under `test262/implementation-contributed` at all.

**Comment by p-bakker** [comment]
K, maybe such test exists in a more recent version of the Test262 suite, but unfortunately we cannot run the latest version, as Rhino misses a bunch of features newer versions of the test suite depends on.

So I guess a dedicated test is in order 🙂

And we're indeed not running the 'implementation contributed' tests: those are contributed to the test262 suite repo for eventual inclusion in the main test suite.

**Comment by gbrail** [comment]
This works great. Thanks!

**Pull request merged**
