### PR TITLE
Math fixes

### PR DESCRIPTION
**Pull request by rbri**
add the missing functions (fixes at least the majority of #200)

### CODE REVIEW

**Comment by rbri** [comment]
Sorry for the conflict, will solve this soon.

**Comment by gbrail** [comment]
This does look good ;-) can you resolve the merge conflict?

**Comment by rbri** [comment]
Locks like this breaks another test.

org.mozilla.javascript.tests.MozillaSuiteTest > runMozillaTest[6563, js=testsrc\tests\js1_5\extensions\regress-363258.js, opt=9] FAILED
    junit.framework.AssertionFailedError at MozillaSuiteTest.java:192

Will require some time to analyze this.

**Comment by rbri** [comment]
Looks like the failing test was a problem with the runtime of the test suite. Have disabled some really slow tests. Now we are ready to merge ;-)

**Comment by gbrail** [comment]
Thanks, will do.

Would you mind squashing this into one or two commits? If it's too
difficult (requires resolving conflicts, etc) then let me know and we'll
leave it.

**Comment by rbri** [comment]
Have created a new PR with only one commit.

**Pull request closed without merging**
