### PR TITLE
improve our test suite

### PR DESCRIPTION
**Pull request by rbri**
we have many more 262 tests passing already - i think we have to use as many tests as possible to check our quality

before: 45858
after:  49719

### CODE REVIEW

**Comment by gbrail** [comment]
Thanks!

I do get the warnings below, running this against the latest merged master. Can you take a look?

    WARN: Exclusion 'entries/primitive-booleans.js' at line #526 doesn't exclude anything
    WARN: Exclusion 'entries/primitive-numbers.js' at line #527 doesn't exclude anything
    WARN: Exclusion 'entries/primitive-strings.js' at line #528 doesn't exclude anything
    WARN: Exclusion 'entries/primitive-symbols.js' at line #529 doesn't exclude anything
    WARN: Exclusion 'getOwnPropertyDescriptors/primitive-booleans.js' at line #555 doesn't exclude anything
    WARN: Exclusion 'getOwnPropertyDescriptors/primitive-numbers.js' at line #556 doesn't exclude anything
    WARN: Exclusion 'getOwnPropertyDescriptors/primitive-strings.js' at line #557 doesn't exclude anything
    WARN: Exclusion 'getOwnPropertyDescriptors/primitive-symbols.js' at line #558 doesn't exclude anything
    WARN: Exclusion 'values/primitive-booleans.js' at line #624 doesn't exclude anything
    WARN: Exclusion 'values/primitive-numbers.js' at line #625 doesn't exclude anything
    WARN: Exclusion 'values/primitive-strings.js' at line #626 doesn't exclude anything
    WARN: Exclusion 'values/primitive-symbols.js' at line #627 doesn't exclude anything

**Comment by rbri** [comment]
Should be fixed at least with one of the next PR's. Please merge and if required i will open a new PR.

**Comment by rbri** [comment]
Have done some checks, the fix is part of PR##455 already. Hope you like this PR also :-)

**Comment by gbrail** [comment]
OK -- that makes sense. Thanks!

**Pull request merged**
