### PR TITLE
Nullish assign operator `??=`

### PR DESCRIPTION
**Pull request by andreabergia**
Implements the nullish assign operator `??=`.

This PR is stacked on top of #1702. The only new commit is this: https://github.com/mozilla/rhino/commit/005371f3fb972ec12ca6af0054008982cf6fbb48

Should close https://github.com/mozilla/rhino/issues/936

### CODE REVIEW

**Comment by andreabergia** [comment]
Rebased on top of master

**Comment by rbri** [comment]
another step forward, like to see this on head - thanks

**Comment by gbrail** [comment]
Thanks -- looking good, just needs another rebase. Thanks!

**Comment by andreabergia** [comment]
> Thanks -- looking good, just needs another rebase. Thanks!

Just done it!

**Comment by gbrail** [comment]
Looks good -- thanks!

**Pull request merged**
