### PR TITLE
FEAT: Implement Symbol.unscopables

### PR DESCRIPTION
**Pull request by 0xe**
Implements `Array.prototype[Symbol.unscopables]` from the [spec](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype-%symbol.unscopables%).

### CODE REVIEW

**Comment by rbri** [comment]
LGTM 👍

**Comment by rbri** [comment]
do we need a feature check for ES6 here?

**Comment by gbrail** [comment]
Looks good and thanks! Can you please re-base on top of the latest to pick up the changes to test262?

**Comment by 0xe** [comment]
> do we need a feature check for ES6 here?

I think we don't initialise Symbol support unless it's ES6. So evaluating any Symbol throws `ReferenceError` in non-es6 which seems to be expected behaviour. I was following what we are doing to `Symbol.species`. 

The [spec](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-symbol-objects) doesn't seem to talk about throwing an different error in older versions when the Symbols are referenced.

**Comment by gbrail** [comment]
Thanks, this makes sense. Any idea why that one remaining test continues to fail -- is it something we can address in another PR?

prototype/Symbol.unscopables/change-array-by-copy.js

**Comment by 0xe** [comment]
> Thanks, this makes sense. Any idea why that one remaining test continues to fail -- is it something we can address in another PR?
> 
> prototype/Symbol.unscopables/change-array-by-copy.js

This test uses `for (const unscopable of [...])` loop which doesn't work in Rhino (we throw syntax error for this form). The same check works if rewritten using `for (var unscopable of [...])` like this:

```javascript
var unscopables = Array.prototype[Symbol.unscopables];

for (var unscopable of ["toReversed", "toSorted", "toSpliced"]) {
    verifyProperty(unscopables, unscopable, {
        value: true,
        writable: true,
        configurable: true
    })
};

assert(!Object.prototype.hasOwnProperty.call(unscopables, "with"), "does not have `with`");
```

**Comment by gbrail** [comment]
OK, thanks for the explanation of the test -- looks good to me.

**Pull request merged**
