### PR TITLE
Report parsing error for default values in destructuring assignments

### LINKED ISSUE #385: IllegalStateException
When evaluating the attached file , an `IllegalStateException` is thrown.
[rhino_ise.zip](https://github.com/mozilla/rhino/files/1691899/rhino_ise.zip)
Rhino version: `1.7.7.2`
Kotlin code to reproduce the issue if `path` points to the attached file:
```
File(path).reader().use {
            val context = Context.enter()
            val scope = context.initStandardObjects()
            context.evaluateReader(scope, it, path, 1, null)
        }
```

### PR DESCRIPTION
**Pull request by sainaen**
Closes #385. (See my comments there for even more context.)

### CODE REVIEW

**Comment by sainaen** [comment]
Travis-CI check failed, because
```
Global vars should not be more than 2.5 times slower than local, Ratio: 2.8160377358490565
```
but I think it’s an intermittent perf problem on the CI servers. The same test passes locally.

**Comment by sainaen** [comment]
Here we go again
```
In "testsrc/tests/ecma_3/RegExp/regress-289669.js":
  FAILED! O(N^2) behavior on String.replace(/RegExp/, ...) BigO 2 < 2 : Expected value 'true', Actual value 'false'
```
😞 

Something weird is going on at Travis-CI. I’ll force rebuild tomorrow morning (UTC+0).

**Comment by sainaen** [comment]
OK, tests did pass in two last runs on Travis CI ([315](https://travis-ci.org/mozilla/rhino/builds/340103135), [319](https://travis-ci.org/mozilla/rhino/builds/341512668)).

**Comment by gbrail** [comment]
Those tests are flaky. I think that they made sense back in the old days
but on a modern CPU and a modern JVM I think that those kinds of benchmarks
are not helpful. I'm happy to disable more of those 'BigO' tests in favor
of actual benchmarks like the ones we currently use (and new ones!)

**Comment by gbrail** [comment]
Looks good -- thanks!

**Pull request merged**
