### PR TITLE
[WIP] Allow Array.prototype methods to handle array-like objects with length greater than 2^32 - 1

### PR DESCRIPTION
**Pull request by sainaen**
According to ES2015 array instance can have a length ≤ 2<sup>32</sup> - 1, but Array.prototype methods allowed to handle array-like objects with `length`-s up to 2<sup>53</sup> - 1, as long as they don't try to create array with such length or update length of existing instance, in those cases TypeError or RangeError should be thrown.

In this PR I've updated `NativeArray.getLengthProperty()` and some other methods to handle those cases properly. 

This will fix `# incorrect length handling` section of ignored test262 cases. 

*Note:* I already have rough version of changes required and because of that I can be sure that it will not fix other ignored cases, so feel free to work on those.

*Note 2:* in added test262, cases that should be fixed with my other PR-s are not ignored, so there will be test failures until those will be merged into master.

### CODE REVIEW

**Comment by gbrail** [comment]
Rebased and merged to master. Thanks!

**Comment by sainaen** [comment]
Huh. You know, when GitHub introduced the advanced search features, one of the things they demoed to show how easy the searching become, was how many pull requests with "do not merge" phrase in them got merged. I laughed then and now I see my PR with 'Work in progress" in the title merged. :laughing: 

Sorry I didn't have time to finish it as fast as I thought, because it took me much more time than I expected to verify that I'm not introducing anything stupid (and I'm not convinced yet). I hope to finish it this week.

Now, I think it would be better to revert commits that were merged. It would unblock #216 which would be nice to have for my work (turns out, some of the cases that are passing with my updates, are actually negative tests that are failing, but I didn't know that.)

**Comment by gbrail** [comment]
OK, sorry -- it looked fairly innocuous and it didn't cause existing tests
to break. Let me revert it and then we can get back to fixing the various
negative tests. We can leave it for future implementation.

I think that in the future it'd be clearer to not open a PR for a "work in
progress" unless it's ready to merge in to master.

On Mon, Jul 27, 2015 at 12:54 PM, Ivan Vyshnevskyi <notifications@github.com
> wrote:

> Huh. You know, when GitHub introduced the advanced search features, one of
> the things they demoed to show how easy the searching become, was how many
> pull requests with "do not merge" phrase in them got merged. I laughed then
> and now I see my PR with 'Work in progress" in the title merged. [image:
> :laughing:]
>
> Sorry I didn't have time to finish it as fast as I thought, because it
> took me much more time than I expected to verify that I'm not introducing
> anything stupid (and I'm not convinced yet). I hope to finish it this week.
>
> Now, I think it would be better to revert commits that were merged. It
> would unblock #216 <https://github.com/mozilla/rhino/pull/216> which
> would be nice to have for my work (turns out, some of the cases that are
> passing with my updates, are actually negative tests that are failing, but
> I didn't know that.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/pull/214#issuecomment-125325394>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>
<http://iloveapis.com/>

**Comment by sainaen** [comment]
@gbrail 
Ok. Sorry for confusion it caused.

**Pull request closed without merging**
