### PR TITLE
Implement ES.next for-of

### PR DESCRIPTION
**Pull request by tuchida**
This patch is implementing for-of syntax which iterates Array and String.
https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Statements/for...of
http://wiki.ecmascript.org/doku.php?id=harmony:iterators

I've used the current ES6 draft (December 21, 2012 Draft) for this patch.
Conflict with for each-in, referred to behavior of Firefox19(Aurora 19.0a2 (2012-12-19)).

### CODE REVIEW

**Comment by gbrail** [comment]
@tuchida -- same question here -- the code has changed quite a bit. 

I had to make a few merges, which I made in the branch "tuchida-for-of_loop". The test passes except for the test on "for (var n of null) {}".

Can you take a look at the branch and see if the merge looks OK to you? I'd also like to see if we can find an external test for this, although I can't find one easily in the V8 test suite.

I think I just wrote this same comment in your own repo -- sorry.

**Comment by tuchida** [comment]
> I'd also like to see if we can find an external test for this, although I can't find one easily in the V8 test suite.

It seems that test262 have begun support of ES6.
https://github.com/tc39/test262/pull/308

As far as I know, my branch does not meet the specification of the following.

 * The specification is `Array.prototype[Symbol.iterator]`, but `Array.prototype.iterator`.
 * surrogate pair
```js
var c = 0;
for (var c of '𠮷野家') {
  c++;
}
c;   // Expect 3, but 4.
```

**Comment by eshepelyuk** [comment]
Hello @tuchida 
1. You could use my simple `Symbol` implementation from PR #203 to implement more spec compatible `for-of` loop.
2. Second thing I would like to ask if it possible to improve this PR by implementing latest version of `Iterator Protocol` as described in [ES 2015 standard](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#iterator)
3. I would also like to use this work for finalizing #159 where `Iterator and Iterable` protocol is widely used. 

So, after those changes we could use more of `test262` suites to prove `for-of` implementation.
What do you think ?

**Comment by tuchida** [comment]
Hello @eshepelyuk

I use your `Symbol`. Does it this will be your help?

**Comment by eshepelyuk** [comment]
Hello

You can use current simple `Symbol` implementation to just make more `test262` tests pass.
But since you've implemented `NativeElementIterator` - you may notice that it works not according to `Iterator protocol`. 
So I asked if you can make this iterator to implement ES6 iterator protocol, so `NativeElementIterator` can be later reused for a variety of ES6 code.

**Comment by eshepelyuk** [comment]
Btw you maybe interested in taking a look at PR #205 that implements sample framework for selectively running test262 as a part of `Rhino` unit tests.

**Comment by tuchida** [comment]
Thanks! `Test262SuiteTest` is cool.

I used the test case and read specification. I want to these iterable objects. I will send PR in future as possible.

## Arguments

> 9.4.4.6 CreateUnmappedArgumentsObject(argumentsList)
>  7. Perform DefinePropertyOrThrow(obj, @@iterator, PropertyDescriptor {[[Value]]:%ArrayProto_values%, [[Writable]]: true, [[Enumerable]]: false, [[Configurable]]: true}).

> 9.4.4.7 CreateMappedArgumentsObject ( func, formals, argumentsList, env )
>  22. Perform DefinePropertyOrThrow(obj, @@iterator, PropertyDescriptor {[[Value]]:%ArrayProto_values%, [[Writable]]: true, [[Enumerable]]: false, [[Configurable]]: true}).

## %TypedArray%

> 22.2.3.30 %TypedArray%.prototype [ @@iterator ] ( )

## java.util.Iterator, java.lang.Iterable

**Comment by eshepelyuk** [comment]
Hello @gbrail 
Is there an chance this PR will be merged soon to master ? 
I'd like to use it for completing implementation of #159. The `iterator protocol` implemented by @tuchida is the last remaining thing for implementing Maps and Sets support for `Rhino`.

**Comment by gbrail** [comment]
Rebased and merged into master. Thanks!

**Pull request closed without merging**
