### PR TITLE
Math fixes2

### PR DESCRIPTION
**Pull request by rbri**
add the missing functions (fixes at least the majority of #200)

### CODE REVIEW

**Comment by rbri** [comment]
maybe i'm too stupid for git

**Comment by gbrail** [comment]
If the rebasing doesn't just happen automatically (and it might not because of conflicts) then we can just merge the first PR -- just let me know. Thanks.

**Comment by rbri** [comment]
please merge the second and squash if you like....

	rbri

On Tue, 03 Jul 2018 17:56:36 +0000 (UTC) Greg Brail wrote:
>
>If the rebasing doesn't just happen automatically (and it might not because of conflicts) 
then we can just merge the first PR -- just let me know. Thanks.
>

**Comment by gbrail** [comment]
I merged this manually and also rebased it a bit. Thanks!

**Pull request closed without merging**
