### PR TITLE
fix border checks for typedarray set

### PR DESCRIPTION
**Pull request by rbri**
(see https://github.com/HtmlUnit/htmlunit-core-js/issues/27)

### CODE REVIEW

**Comment by gbrail** [comment]
Looks good and thanks -- one suggestion if you have time, though -- since you're changing this, would it be difficult to put those rangeError messages in mesages.properties instead?

**Comment by rbri** [comment]
@gbrail good point will do that tomorrow

**Comment by rbri** [comment]
@done, have added some missing tests for that messages also

**Comment by gbrail** [comment]
Looks good!

**Pull request merged**
