### PR TITLE
some jvmbridge cleanup

### PR DESCRIPTION
**Pull request by rbri**
; jdk 1.3 support is no longer needed, all implementations are protected, some methods removed because of simplification

### CODE REVIEW

**Comment by gbrail** [comment]
Thanks for cleaning this up!

**Comment by rbri** [comment]
Anything i can do to get this also merged?
My plan was to do this as a first step and remove some of the methods from the interface. For a next step we can discuss the removal of more methods from the interface (at least for performance reasons this might make sense)

**Comment by gbrail** [comment]
It seems OK to me but it's bigger so I wanted to read it more carefully.

**Comment by gbrail** [comment]
Rebased and merged.

**Pull request closed without merging**
